## handling Implaced Dataset
### 1- Up Sampling
### 2- Down Sampling

In [2]:
import numpy as np
import pandas as pd

# set the random seed for reprofuctivity
np.random.seed(123)

# Create a dataframes with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [3]:
n_class_0, n_class_1

(900, 100)

In [4]:
# CREATE A DATFRAME WITH INBALANCED DATASET
class_0 = pd.DataFrame({
    'feature_1' : np.random.normal(loc=0,scale=1,size=n_class_0),
    'feature_2' : np.random.normal(loc=0,scale=1,size=n_class_0),
    'target': [0] * n_class_0
})
class_1 = pd.DataFrame({
    'feature_1' : np.random.normal(loc=2,scale=1,size=n_class_1),
    'feature_2' : np.random.normal(loc=2,scale=1,size=n_class_1),
    'target':[1] * n_class_1
})

In [5]:
df=pd.concat([class_0,class_1]).reset_index(drop=True)

In [6]:
df.head()

   feature_1  feature_2  target
0  -1.085631   0.551302       0
1   0.997345   0.419589       0
2   0.282978   1.815652       0
3  -1.506295  -0.252750       0
4  -0.578600  -0.292004       0

In [7]:
df.tail()

     feature_1  feature_2  target
995   1.376371   2.845701       1
996   2.239810   0.880077       1
997   1.131760   1.640703       1
998   2.902006   0.390305       1
999   2.697490   2.013570       1

In [8]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [9]:
## Upsampling
df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [18]:
pip install sklearn.utils

Collecting sklearn.utils
  Downloading sklearn_utils-0.0.15.tar.gz (26 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: numpy in c:\Users\DELL\venv\Lib\site-packages (from sklearn.utils) (2.4.4)
Collecting pyfunctional (from sklearn.utils)
  Downloading pyfunctional-1.5.0-py3-none-any.whl.metadata (40 kB)
Requirement already satisfied: pandas in c:\Users\DELL\venv\Lib\site-packages (from sklearn.utils) (3.0.3)
Requirement already satisfied: scipy in c:\Users\DELL\venv\Lib\site-packages (from sklearn.utils) (1.17.1)
Collecting scikit-learn (from sklearn.utils)
  Downloading scikit_learn-1.9.0-cp312-cp312-win_amd64.whl.metadata (11 kB)
Collecting statsmodels (from sklearn.utils)
  Downloading statsmodels-0.14.6-cp312-cp312-win_amd64.whl.metadata (9.8 kB)
Requirement already satisfied: seaborn in c:\Users\DELL\venv\Lib\site-packages (from sklearn.utils) (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\DELL\venv\Lib\site-packages (from pandas->sklearn.utils) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\DELL\venv\Lib\site-packages (from pandas->sklearn.utils) (2026.2)
Requirement already satisfied: six>=1.5 in c:\Users\DELL\venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas->sklearn.utils) (1.17.0)
Collecting dill>=0.2.5 (from pyfunctional->sklearn.utils)
  Downloading dill-0.4.1-py3-none-any.whl.metadata (10 kB)
Collecting tabulate<=1.0.0 (from pyfunctional->sklearn.utils)
  Downloading tabulate-0.10.0-py3-none-any.whl.metadata (40 kB)
Collecting joblib>=1.4.0 (from scikit-learn->sklearn.utils)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn->sklearn.utils)
  Downloading narwhals-2.22.1-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn->sklearn.utils)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\Users\DELL\venv\Lib\site-packages (from seaborn->sklearn.utils) (3.10.9)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\DELL\venv\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->sklearn.utils) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\Users\DELL\venv\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->sklearn.utils) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\Users\DELL\venv\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->sklearn.utils) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\DELL\venv\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->sklearn.utils) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\Users\DELL\venv\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->sklearn.utils) (26.0)
Requirement already satisfied: pillow>=8 in c:\Users\DELL\venv\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->sklearn.utils) (12.2.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\DELL\venv\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->sklearn.utils) (3.3.2)
Collecting patsy>=0.5.6 (from statsmodels->sklearn.utils)
  Downloading patsy-1.0.2-py2.py3-none-any.whl.metadata (3.6 kB)
Downloading pyfunctional-1.5.0-py3-none-any.whl (53 kB)
Downloading tabulate-0.10.0-py3-none-any.whl (39 kB)
Downloading dill-0.4.1-py3-none-any.whl (120 kB)
Downloading scikit_learn-1.9.0-cp312-cp312-win_amd64.whl (8.2 MB)
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.2 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.2 MB 1.0 MB/s eta 0:00:08
   -- ------------------------------------- 0.5/8.2 MB 1.0 MB/s eta 0:00:08
   ----- ---------------------------------- 1.0/8.2 MB 949.8 kB/s eta 0:00:08
   ------ --------------------------------- 1.3/8.2 MB 1.0 MB/s eta 0:00:07
   ------- -------------------------------- 1.6/8.2 MB 1.0 MB/s eta 0:00:07
   -------- ------------------------------- 1.8/8.2 MB 1.1 MB/s eta 0:00:06
   ---------- ----------------------------- 2.1/8.2 MB 1.1 MB/s eta 0:00:06
   ----------- ---------------------------- 2.4/8.2 MB 1.1 MB/s eta 0:00:06
   ------------ --------------------------- 2.6/8.2 MB 1.1 MB/s eta 0:00:05
   -------------- ------------------------- 2.9/8.2 MB 1.2 MB/s eta 0:00:05
   --------------- ------------------------ 3.1/8.2 MB 1.2 MB/s eta 0:00:05
   ---------------- ----------------------- 3.4/8.2 MB 1.2 MB/s eta 0:00:05
   ------------------- -------------------- 3.9/8.2 MB 1.3 MB/s eta 0:00:04
   -------------------- ------------------- 4.2/8.2 MB 1.3 MB/s eta 0:00:04
   --------------------- ------------------ 4.5/8.2 MB 1.3 MB/s eta 0:00:03
   ------------------------ --------------- 5.0/8.2 MB 1.3 MB/s eta 0:00:03
   ------------------------- -------------- 5.2/8.2 MB 1.3 MB/s eta 0:00:03
   ---------------------------- ----------- 5.8/8.2 MB 1.3 MB/s eta 0:00:02
   ----------------------------- ---------- 6.0/8.2 MB 1.4 MB/s eta 0:00:02
   --------------------------------- ------ 6.8/8.2 MB 1.5 MB/s eta 0:00:01
   ----------------------------------- ---- 7.3/8.2 MB 1.5 MB/s eta 0:00:01
   ---------------------------------------  8.1/8.2 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------- 8.2/8.2 MB 1.6 MB/s  0:00:05
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading narwhals-2.22.1-py3-none-any.whl (454 kB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Downloading statsmodels-0.14.6-cp312-cp312-win_amd64.whl (9.5 MB)
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.5 MB 3.7 MB/s eta 0:00:03
   ----- ---------------------------------- 1.3/9.5 MB 3.0 MB/s eta 0:00:03
   ------ --------------------------------- 1.6/9.5 MB 2.4 MB/s eta 0:00:04
   -------- ------------------------------- 2.1/9.5 MB 2.5 MB/s eta 0:00:03
   ---------- ----------------------------- 2.6/9.5 MB 2.6 MB/s eta 0:00:03
   -------------- ------------------------- 3.4/9.5 MB 2.6 MB/s eta 0:00:03
   ---------------- ----------------------- 3.9/9.5 MB 2.6 MB/s eta 0:00:03
   ------------------ --------------------- 4.5/9.5 MB 2.6 MB/s eta 0:00:02
   --------------------- ------------------ 5.2/9.5 MB 2.7 MB/s eta 0:00:02
   ------------------------- -------------- 6.0/9.5 MB 2.8 MB/s eta 0:00:02
   --------------------------- ------------ 6.6/9.5 MB 2.8 MB/s eta 0:00:02
   ----------------------------- ---------- 7.1/9.5 MB 2.8 MB/s eta 0:00:01
   -------------------------------- ------- 7.9/9.5 MB 2.8 MB/s eta 0:00:01
   ----------------------------------- ---- 8.4/9.5 MB 2.8 MB/s eta 0:00:01
   ------------------------------------- -- 8.9/9.5 MB 2.8 MB/s eta 0:00:01
   ---------------------------------------  9.4/9.5 MB 2.8 MB/s eta 0:00:01
   ---------------------------------------- 9.5/9.5 MB 2.7 MB/s  0:00:03
Downloading patsy-1.0.2-py2.py3-none-any.whl (233 kB)
Building wheels for collected packages: sklearn.utils
  Building wheel for sklearn.utils (pyproject.toml): started
  Building wheel for sklearn.utils (pyproject.toml): finished with status 'done'
  Created wheel for sklearn.utils: filename=sklearn_utils-0.0.15-py3-none-any.whl size=27951 sha256=de2d8ff4f8d3d8078ab5d56368ed1c753a8652511e9441cc4ba0345a28e64c74
  Stored in directory: c:\users\dell\appdata\local\pip\cache\wheels\ed\ed\51\21a8cdae39ae51a93bcb2d2f092e5cf722255d42147df1e4bf
Successfully built sklearn.utils
Installing collected packages: threadpoolctl, tabulate, patsy, narwhals, joblib, dill, scikit-learn, pyfunctional, statsmodels, sklearn.utils

   ---- -----------------------------------  1/10 [tabulate]
   ---- -----------------------------------  1/10 [tabulate]
   -------- -------------------------------  2/10 [patsy]
   -------- -------------------------------  2/10 [patsy]
   -------- -------------------------------  2/10 [patsy]
   -------- -------------------------------  2/10 [patsy]
   -------- -------------------------------  2/10 [patsy]
   -------- -------------------------------  2/10 [patsy]
   -------- -------------------------------  2/10 [patsy]
   -------- -------------------------------  2/10 [patsy]
   -------- -------------------------------  2/10 [patsy]
   -------- -------------------------------  2/10 [patsy]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ------------ ---------------------------  3/10 [narwhals]
   ---------------- -----------------------  4/10 [joblib]
   ---------------- -----------------------  4/10 [joblib]
   ---------------- -----------------------  4/10 [joblib]
   ---------------- -----------------------  4/10 [joblib]
   ---------------- -----------------------  4/10 [joblib]
   ---------------- -----------------------  4/10 [joblib]
   ---------------- -----------------------  4/10 [joblib]
   ---------------- -----------------------  4/10 [joblib]
   ---------------- -----------------------  4/10 [joblib]
   ---------------- -----------------------  4/10 [joblib]
   ---------------- -----------------------  4/10 [joblib]
   ---------------- -----------------------  4/10 [joblib]
   ---------------- -----------------------  4/10 [joblib]
   ---------------- -----------------------  4/10 [joblib]
   ---------------- -----------------------  4/10 [joblib]
   ---------------- -----------------------  4/10 [joblib]
   ---------------- -----------------------  4/10 [joblib]
   ---------------- -----------------------  4/10 [joblib]
   ---------------- -----------------------  4/10 [joblib]
   ---------------- -----------------------  4/10 [joblib]
   ---------------- -----------------------  4/10 [joblib]
   ---------------- -----------------------  4/10 [joblib]
   ---------------- -----------------------  4/10 [joblib]
   -------------------- -------------------  5/10 [dill]
   -------------------- -------------------  5/10 [dill]
   -------------------- -------------------  5/10 [dill]
   -------------------- -------------------  5/10 [dill]
   -------------------- -------------------  5/10 [dill]
   -------------------- -------------------  5/10 [dill]
   -------------------- -------------------  5/10 [dill]
   -------------------- -------------------  5/10 [dill]
   -------------------- -------------------  5/10 [dill]
   -------------------- -------------------  5/10 [dill]
   -------------------- -------------------  5/10 [dill]
   -------------------- -------------------  5/10 [dill]
   -------------------- -------------------  5/10 [dill]
   -------------------- -------------------  5/10 [dill]
   -------------------- -------------------  5/10 [dill]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]
   ------------------------ ---------------  6/10 [scikit-learn]

In [12]:
from sklearn.utils import resample
df_minority_upsampled=resample(df_minority,replace=True,
n_samples =len(df_majority),
random_state=42
)

In [13]:
df_minority_upsampled.shape

(900, 3)

In [14]:
df_minority_upsampled.head()

     feature_1  feature_2  target
951   1.125854   1.843917       1
992   2.196570   1.397425       1
914   1.932170   2.998053       1
971   2.272825   3.034197       1
960   2.870056   1.550485       1

In [15]:
df_upsampled=pd.concat([df_majority,df_minority_upsampled])

In [17]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

In [18]:
## Down Sapmling
# CREATE A DATFRAME WITH INBALANCED DATASET
class_0 = pd.DataFrame({
    'feature_1' : np.random.normal(loc=0,scale=1,size=n_class_0),
    'feature_2' : np.random.normal(loc=0,scale=1,size=n_class_0),
    'target': [0] * n_class_0
})
class_1 = pd.DataFrame({
    'feature_1' : np.random.normal(loc=2,scale=1,size=n_class_1),
    'feature_2' : np.random.normal(loc=2,scale=1,size=n_class_1),
    'target':[1] * n_class_1
})

df = pd.concat([class_0, class_1]).reset_index(drop=True)

## Check the class distribution
print(df['target'].value_counts())

target
0    900
1    100
Name: count, dtype: int64

In [19]:
from sklearn.utils import resample
df_majority_downSampled=resample(df_majority,replace=False,
n_samples =len(df_minority),
random_state=42
)

In [20]:
df_majority_downSampled.shape

(100, 3)

In [22]:
df_downsampled=pd.concat([df_minority,df_majority_downSampled])

In [23]:
df_downsampled['target'].value_counts()

target
1    100
0    100
Name: count, dtype: int64